### ISSUE TITLE
Admin page is broken. 

### ISSUE THREAD

**Issue by benevbright** [nishi-ai/softball-register-server#31]
Not sure if it's web or server but it goes to 500 page on Admin

### reproduce
- go http://berlin.catsdogssoftball.com/admin
- type any letters and enter
It goes to 500 page.

**Comment by nishi-ai** [comment]
error message on the latest code. 
Failing to fetch
<img width="848" alt="Screenshot 2021-12-09 at 06 58 58" src="https://user-images.githubusercontent.com/60405643/145342666-ab0bc797-9dd2-477a-9328-fe0acccbd1a4.png">

Some questions:
- Was here supposed to be 'POST' method? to send the password?
- API Url should be `${apiUrl}/admin/players/?password=${adminPassword}` or `${apiUrl}/admin/players/`?
- Regarding the web: LoginToAdminPage.js line 44 setCallLoading(true)
 when I put console.log(callLoading) after this line, it shows 'false'.  Why is it false, although the loader infinitely is loading because of failure of fetching?

**Comment by benevbright** [comment]
> Was here supposed to be 'POST' method? to send the password?

It depends on what kind of type the call is. If it's to 'get' something, GET is normally used. And we've implemented as "GET" in server. So it should be GET call https://github.com/nishi-ai/softball-register-server/blob/d190795f7afbdd78f1679529a27c26f833df6603/routes/admin.js?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L11 .

> API Url should be ${apiUrl}/admin/players/?password=${adminPassword} or ${apiUrl}/admin/players/?

The old webapp sends like the first and the new webapp (if it's been deployed correctly after merging) would send like the second. Both should work.

**Comment by benevbright** [comment]
> Regarding the web: LoginToAdminPage.js line 44 setCallLoading(true)
when I put console.log(callLoading) after this line, it shows 'false'. Why is it false, although the loader infinitely is loading because of failure of fetching?

Good question! It's a tricky part of React. The reason why it's `false` is that React updates its `state` asynchronously after we call `setSOMESTATE`. Meaning, React updates them with a little bit of delay. 

So when you checked it right way, it's still `false` but React would update it shortly. 

Here is a nice explanation: https://stackoverflow.com/questions/36085726/why-is-setstate-in-reactjs-async-instead-of-sync

**Comment by benevbright** [comment]
@nishi-ai I've answered your question! :)
